
main: net.zylve.zutil.Main
name: zUtil
version: 0.0.1
api-version: 1.17

commands:
  shout:
    description: Show your current coordinates
    usage: "Usage: /<command>"
  rlc:
    description: Alias for /reload confirm
    usage: "Usage: /<command>"
  getip:
    description: This Bukkit command exists for legacy reasons.
    usage: "Usage: /<command> <username>"
  sudo:
    description: le funny
  stackcount:
    description: Get the amount of shulkers, stacks, and items needed for any number.
    usage: "Usage: /<command> <number>"
    aliases: [ sc ]
  coordinatesconsent:
    description: Manage who can get your coordinates
    usage: "Usage /<command> [add|remove|list|clear]"
    aliases: [ cc ]