
main: net.zylve.zutil.Main
name: ZylveUtil
version: 0.0.1
api-version: 1.17

commands:
  shout:
    description: Show your current coordinates
    usage: /shout
  rlc:
    description: Alias for /reload confirm
    usage: /rlc
  getip:
    description: This Bukkit command exists for legacy reasons.
    usage: /getip